### ISSUE TITLE
GUI problem since last week on iOS

### ISSUE THREAD

**Issue by sebastesnorvegicus** [gautemo/ordle#14]
After flickering only first letter is displayed.
Attached file shows a page refresh on a finished game, but it happens during play as well.
I upgraded to iOS 16.2 last week.

https://user-images.githubusercontent.com/32516062/213404492-13d3c8ac-62b5-4741-b6d0-01b658c6b3bd.mov

**Comment by gautemo** [comment]
Thanks for the video. I don't know why this happens. But it looks like the safari version can't transform the input with the text correctly. I have others that have said the same thing. 

I thought I could detect the safari version on this commit https://github.com/gautemo/ordle/commit/885ca5b380e7853bdb9bff8a21818136adbe2bb4, but maybe the check is not working correctly. Any idea what `navigator.userAgent` is for you? I tried creating a codesandbox that prints it if you try https://mmxz69.csb.app/ (hope it works)

But you can also turn it off in settings so you can keep playing.
![turn off animation](https://user-images.githubusercontent.com/6643053/213539846-cd53d5b1-91f5-4c47-a8f4-8d522db1544f.png)

**Comment by sebastesnorvegicus** [comment]
Safari:

Mozilla/5.0 (iPhone; CPU iPhone OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Mobile/15E148 Safari/604.1

**Comment by gautemo** [comment]
> Safari:
> 
> Mozilla/5.0 (iPhone; CPU iPhone OS 16_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Mobile/15E148 Safari/604.1

Thank you, I've tried to update the is Safari v16.2 check so it will turn off the animation automatically. 

Otherwise, I will just have to see if they fix it in the next version or if there are some CSS properties that can fix this.

**Comment by sebastesnorvegicus** [comment]
Problem solved in iOS 16.3:
- option "Uten animasjoner" is back
- when unchecked animation works

I see no way this issue could have been handled better. 
Thanks 😊
